#INITIAL SETTINGS
data_directory: data/
raw_data: data/raw/
train_test_data: data/processed/
synthetic_data: data/interim/
train_data: train_df.csv
test_data: test_df.csv
synth_train_data: train_synthetic.csv
synth_test_data: test_synthetic.csv
data: heart_cleveland_upload.csv
path_to_reports: reports
pd_report: output_pd_profiling.html
sweetviz_report: sweet_report.html
logs_path: logs
data_log: data.log
train_log: logfile_for_train.log
predict_log: logfile_for_predict.log
categ_features: ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal']
numerical_features: ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
synth_train_size: 200
drop_columns: ["id"]
target_name: condition
test_size: 0.2
model_directory: ../models/
model_name: KNN_classifier.pkl
model: LogisticRegression # KNN
y_pred_path: models/


#LogisticRegression parameters
max_iter: 500
